### ISSUE TITLE
error when no snp col is provided

### ISSUE THREAD

**Issue by mcgml** [MRCIEU/gwas2vcf#29]
```
2019-11-21 21:18:12,876 INFO GWAS2VCF 1.1.1
2019-11-21 21:18:12,876 INFO Arguments: {'out': '/data/gwas2vcfweb/data/64d840d6-0ca4-11ea-a24a-0242ad006803/64d840d6-0ca4-11ea-a24a-0242ad006803_harm.vcf.gz', 'data': '/data/gwas2vcfweb/cromwell-executions/gwas2vcf/c320d28f-76ca-4bff-886b-48e04209f86c/call-vcf/inputs/1204249195/64d840d6-0ca4-11ea-a24a-0242ad006803.txt', 'ref': '/data/gwas2vcfweb/cromwell-executions/gwas2vcf/c320d28f-76ca-4bff-886b-48e04209f86c/call-vcf/inputs/1899004205/human_g1k_v37.fasta', 'json': '/data/gwas2vcfweb/cromwell-executions/gwas2vcf/c320d28f-76ca-4bff-886b-48e04209f86c/call-vcf/inputs/1204249195/upload.json', 'id': '64d840d6-0ca4-11ea-a24a-0242ad006803', 'cohort_controls': None, 'cohort_cases': None, 'rm_chr_prefix': True, 'csi': False, 'log': 'INFO'}
2019-11-21 21:18:12,876 INFO Reading JSON parameters
2019-11-21 21:18:12,877 INFO Parameters: {'header': True, 'delimiter': '\t', 'pval_col': 8, 'beta_col': 5, 'pos_col': 1, 'build': 'GRCh37', 'ea_col': 3, 'chr_col': 0, 'oa_col': 4, 'se_col': 6}
2019-11-21 21:18:12,877 INFO Checking input arguments
2019-11-21 21:18:12,877 INFO Reading summary stats and mapping to FASTA: /data/gwas2vcfweb/cromwell-executions/gwas2vcf/c320d28f-76ca-4bff-886b-48e04209f86c/call-vcf/inputs/1204249195/64d840d6-0ca4-11ea-a24a-0242ad006803.txt
2019-11-21 21:18:12,878 INFO Reading plain text file
2019-11-21 21:18:12,878 INFO Skipping header: chr	pos	rsid	A1	A2	beta	se	N	P-value	Freq.A1.1000G.EUR
2019-11-21 21:18:12,916 INFO Total variants: 999
2019-11-21 21:18:12,916 INFO Variants could not be read: 0
2019-11-21 21:18:12,926 INFO Variants harmonised: 999
2019-11-21 21:18:12,926 INFO Variants discarded during harmonisation: 0
2019-11-21 21:18:12,926 INFO Alleles switched: 455
2019-11-21 21:18:12,926 INFO Skipped 0 of 999
2019-11-21 21:18:12,926 INFO Writing headers to BCF/VCF: /data/gwas2vcfweb/data/64d840d6-0ca4-11ea-a24a-0242ad006803/64d840d6-0ca4-11ea-a24a-0242ad006803_harm.vcf.gz
Traceback (most recent call last):
  File "/app/main.py", line 175, in <module>
    main()
  File "/app/main.py", line 171, in main
    Vcf.write_to_file(harmonised, args.out, fasta, j['build'], args.id, sample_metadata, file_metadata, args.csi)
  File "/app/vcf.py", line 149, in write_to_file
    record.id = Vcf.remove_illegal_chars(result.dbsnpid)
  File "/app/vcf.py", line 30, in remove_illegal_chars
    r = s.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by mcgml** [comment]
https://github.com/MRCIEU/gwas2vcf/commit/d18347a7b74f45a5d7cf0c441cbd353c62fb6831
